### ISSUE TITLE
Login Page of web portal is buggy

### ISSUE THREAD

**Issue by FamALouiz** [Brogammers/QMaster#148]
When opening the web portal on firefox (not sure if the issue is firefox related), the text boxes for email and password do not appear on the screen and appear on the right. I believe this might be an issue with the screen size.

**Comment by CodeNKoffee** [comment]
@FamALouiz can you please provide screenshots here on this issue and create a bug ticket on JIRA? I need everything documented so I don't miss anything. Thanks in advance.

**Comment by FamALouiz** [comment]
![Screenshot 2024-04-16 174438](https://github.com/Brogammers/QMaster/assets/88089745/a9e3ecfa-6ffc-4a8c-99a9-726c8d76f0ec)
Check this bug out 

When zooming out, it does not zoom the background
